#!/bin/bash

echo "Gathering info to generate build info header..."

pwd

build_date=$(date)

git_user=$(git config user.name)


if [[ $git_user ]]; then
  echo "$git_user"
else
  echo "Git user name not set -- please run: git config --global user.name your-name-here"
  exit 1
fi

git_email=$(git config user.email)
if [[ $git_email ]]; then
  echo "$git_email"
else  echo  "Git user email not set -- please run: git config --global user.email your-email-here"
  exit 1
fi

git_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $git_branch ]]; then
  echo "$git_branch"
else
  echo "Failed to determine current git branch"
  exit 1
fi


git_count=$(git rev-list --count HEAD)

if [[ $git_count ]]; then
  echo "$git_count"
else
  echo "Failed to determine commit count"
  exit 1
fi

git_source_info="$git_branch-$git_count"
os_info=$(cut -d' ' -f2- <<< $(lsb_release -d))
git_log=$(git log --oneline --decorate=no -n 5)
gcc_version=$(arm-none-eabi-gcc --version | grep eabi)


build_id_file="./LPC2136_FreeRTOS_CoreIPM/src/build_id.h"


echo "// This file is autogenerated by build_id.sh script"  > $build_id_file
echo "#ifndef MMC_BUILD_ID_H" >> $build_id_file
echo "#define MMC_BUILD_ID_H" >> $build_id_file
echo " " >> $build_id_file

# build info to header file
echo "#define MMC_BUILD_ID \"\\"           >> $build_id_file
echo "-- Build info -----------------------\n\\">> $build_id_file
echo "Project     : FTRN AMC MMC\n\\"           >> $build_id_file
echo "Build date  : $build_date\n\\"            >> $build_id_file
echo "Prepared by : $git_user <$git_email>\n\\" >> $build_id_file
echo "Source info : $git_source_info\n\\"       >> $build_id_file
echo "OS version  : $os_info\n\\"               >> $build_id_file
echo "Compiler    : $gcc_version\n\\"           >> $build_id_file
echo "\n\\"                                     >> $build_id_file

while IFS= read -r log_line
do
  echo "$log_line\n\\" >> $build_id_file
done <<< "$git_log"


echo "\n\n\"" >> $build_id_file

echo "" >> $build_id_file
echo "#endif" >> $build_id_file
echo "" >> $build_id_file



#write FW info to header file - read by MCH/ipmitool
fw_info_header="./LPC2136_FreeRTOS_CoreIPM/src/fw_info.h"

echo "// This file is autogenerated by build_id.sh script"  > $fw_info_header

echo "#ifndef FW_BUILD_INFO_H" >> $fw_info_header
echo "#define FW_BUILD_INFO_H" >> $fw_info_header

echo "// Shorter version of FW info to be read by MCH/ipmitool" >> $fw_info_header

echo "#define MMC_FW_INFO_0  \"github.com/GSI-CS-CO/mtca_mmc_firmware\"" >> $fw_info_header
echo "#define MMC_FW_INFO_1  \"Branch: $git_branch\"" >> $fw_info_header


git_log="$(git log --decorate=no -n 1)"

#read -r log_line_hash log_line_comment <<< "$git_log"
commit_hash=`echo "$git_log" | grep commit`
author_name=`echo "$git_log" | grep Author`
date_value=`echo "$git_log" | grep Date`


echo "#define MMC_FW_INFO_2  \"$commit_hash\"" >> $fw_info_header
echo "#define MMC_FW_INFO_3  \"$author_name\"" >> $fw_info_header
echo "#define MMC_FW_INFO_4  \"$date_value\"" >> $fw_info_header


echo "" >> $fw_info_header
echo "#endif" >> $fw_info_header
echo "" >> $fw_info_header

