// This file is autogenerated by build_id.sh script
#ifndef FW_BUILD_INFO_H
#define FW_BUILD_INFO_H
// Shorter version of FW info to be read by MCH/ipmitool
#define MMC_FW_INFO_0  "github.com/GSI-CS-CO/mtca_mmc_firmware"
#define MMC_FW_INFO_1  "Branch: master"
#define MMC_FW_INFO_2  "commit 781a5269c632bbdf9cb69bc4c2fbd9e163ffaa82"
#define MMC_FW_INFO_3  "Build Date: Fri Aug 24 16:33:15 CEST 2018"
#define MMC_FW_INFO_4  "By: Dusan Slavinec <dusan.slavinec@cosylab.com>"

#endif

